name: temple_adventures
description: Temple Adventures Mobile Admin App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.1+29

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #-----------------------------------------

  #------------------------------------------
  #           State Management and Storage

  get: ^4.1.4
  get_storage: ^2.0.2
  #------------------------------------------
  #------------------------------------------
  #           Network & Testing
  #------------------------------------------
  #------------------------------------------
  #           UI and Animations



  font_awesome_flutter: ^9.0.0
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+2
  step_progress_indicator: ^1.0.1
  image_cropper: ^1.4.1
  http: ^0.13.3
  permission_handler: ^9.0.2
  file_picker: ^4.4.0
  geolocator: ^8.0.5
  location: ^4.3.0
  fluttertoast:
  flutter_datetime_picker: ^1.5.1
  path_provider: ^2.0.2
  share: ^2.0.4
  dio: ^4.0.1
  url_launcher: ^6.0.12
  search_widget: ^1.0.2
  shimmer: ^2.0.0
  scroll_to_index:
  animated_splash_screen: ^1.1.0
  flutter_native_splash:
  flutter_launcher_icons:
  separated_row: ^2.0.0


  #------------------------------------------
  #------------------------------------------
  #             Auth and Firebase

  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  cloud_firestore: ^3.1.9
  firebase_storage: ^10.0.1
  firebase_messaging: ^11.2.7
  flutter_local_notifications: ^9.4.0
  ota_update: ^4.0.1
  flutter_app_installer: ^0.0.3
  in_app_update: ^3.0.0
  package_info_plus: ^1.4.0

  #------------------------------------------


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - images/
    - images/assets/
    - assets/PDFs/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-Black.ttf
        - asset: fonts/Nunito/Nunito-BlackItalic.ttf
        - asset: fonts/Nunito/Nunito-Bold.ttf
        - asset: fonts/Nunito/Nunito-BoldItalic.ttf
        - asset: fonts/Nunito/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito/Nunito-ExtraBoldItalic.ttf
        - asset: fonts/Nunito/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito/Nunito-ExtraLightItalic.ttf
        - asset: fonts/Nunito/Nunito-Italic.ttf
        - asset: fonts/Nunito/Nunito-LightItalic.ttf
        - asset: fonts/Nunito/Nunito-Regular.ttf
        - asset: fonts/Nunito/Nunito-SemiBold.ttf
        - asset: fonts/Nunito/Nunito-SemiBoldItalic.ttf
