// var d = {
//   "addressLine1": "heh",
//   "addressLine2": "bejjeje",
//   "city": "Nahrīn",
//   "country": "Afghanistan",
//   "countryCode": "+91",
//   "dob": "16 Oct 2021",
//   "email": "hwyhej@gmail.com",
//   "gender": "Female",
//   "location": "Delhi",
//   "name": "behjbshj",
//   "idProof": "behjbshj",
//   "phoneNumber": "6354664646",
//   "pinCode": "655566",
//   "state": "Baghlan",
// };
