// import '../models/checklist_model.dart';
//
// List<ChecklistElement> checkListElements = [
//   ChecklistElement(
//     items: [
//       'BCD',
//       'Regulator',
//       'Mask',
//       'Fins',
//       'Boots',
//       'Wetsuit',
//       'Cargo Shorts',
//       'Sharkskin',
//       '== Green Box',
//       'Computer',
//       'SMBs',
//       'Reels',
//       'Cutting Device',
//       'Compass',
//       'Torch',
//       '== Green Dry Bag',
//       'Medical Kit',
//       'Tool kit',
//       'Student Computer',
//       'Student Equipment',
//       'Student Snorkel',
//       'Student Wetsuit',
//       'Student Weights',
//     ],
//     name: 'Recreational Student Dive Checklist',
//     description:
//         'This checklist should be performed on every Recreational Student Dive.',
//     employeeId: null,
//     id: '',
//   ),
//   ChecklistElement(
//     items: [
//       'BCD',
//       'Regulator',
//       'Mask',
//       'Fins',
//       'Boots',
//       'Wetsuit',
//       'Cargo Shorts',
//       'Sharkskin',
//       '== Green Box',
//       'Computer',
//       'SMBs',
//       'Reels',
//       'Cutting Device',
//       'Compass',
//       'Torch',
//       '== Green Dry Bag',
//       'Medical Kit',
//       'Tool kit',
//     ],
//     title: 'Recreational Dive Checklist',
//     description:
//         'This checklist should be performed on every Recreational Dive.',
//     employeeId: null,
//     id: '',
//   ),
// ];
