import '../models/checklist_model.dart';

List<Checklist> checkLists = [
  Checklist(
    items: [
      'BCD',
      'Regulator',
      'Mask',
      'Fins',
      'Boots',
      'Wetsuit',
      'Cargo Shorts',
      'Sharkskin',
      '== Green Box',
      'Computer',
      'SMBs',
      'Reels',
      'Cutting Device',
      'Compass',
      'Torch',
      '== Green Dry Bag',
      'Medical Kit',
      'Tool kit',
      'Student Computer',
      'Student Equipment',
      'Student Snorkel',
      'Student Wetsuit',
      'Student Weights',
    ],
    name: 'Recreational Student Dive Checklist',
    description: 'This checklist should be performed on every Recreational Student Dive.',
  ),
  Checklist(
    items: [
      'BCD',
      'Regulator',
      'Mask',
      'Fins',
      'Boots',
      'Wetsuit',
      'Cargo Shorts',
      'Sharkskin',
      '== Green Box',
      'Computer',
      'SMBs',
      'Reels',
      'Cutting Device',
      'Compass',
      'Torch',
      '== Green Dry Bag',
      'Medical Kit',
      'Tool kit'
    ],
    name: 'Recreational Dive Checklist',
    description: 'This checklist should be performed on every Recreational Dive.',
  ),
];
